### ISSUE TITLE
CUDA error :too many resources requested for lauch

### ISSUE THREAD

**Issue by leoShen917** [cmusatyalab/mega-nerf-viewer#3]
Hi  @hturki !
I was trying to compile mega-nerf-viewer but was stuck in the final stage.Do you have any idea about this problem?

OS: Ubuntu 20.04
gcc version: 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
cmake: 3.23.1
libtorch  https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.10.0+cu113(cxx11 ABI)
cuda: 11.3

 I have successfully compiled mega-nerf-viewer. Then I ran the following commands with one NVIDIA RTX A6000:
`./mega-nerf-viewer "/data/shenliao/mega-nerf/octree.npz" --model_path "/data/shenliao/mega-nerf/checkpoints/building-pixsfm-8.pt"`

and got:
![cfb2384023cd26682758373c3574e95](https://user-images.githubusercontent.com/83259959/168637157-b8735acd-af9b-468f-852c-fc6b7312a8ff.jpg)

Thanks!

**Comment by hturki** [comment]
I haven't tested it out with an A6000 myself, but could you try lowering the number of cores in https://github.com/cmusatyalab/mega-nerf-viewer/blob/8215314e0a3d66bc3829bdbd098162eb8d7e45c3/src/cuda/renderer_kernel.cu#L14 and see if you still run into errors?

**Comment by leoShen917** [comment]
I have successfully run mega-nerf-viewer just now! You are correct. I lowed the cuda_n_threads and it worked.Thank you for your help! @hturki 
![IMG_20220602_170717](https://user-images.githubusercontent.com/83259959/171994286-2e534727-020b-4876-b478-4e990f8d34eb.jpg)

**Comment by ZiyangYan** [comment]
> I haven't tested it out with an A6000 myself, but could you try lowering the number of cores in
> 
> https://github.com/cmusatyalab/mega-nerf-viewer/blob/8215314e0a3d66bc3829bdbd098162eb8d7e45c3/src/cuda/renderer_kernel.cu#L14
> 
> and see if you still run into errors?

I decreased the number very small, but the problem still exist, my GPU is RTX3080TI.
![image](https://github.com/cmusatyalab/mega-nerf-viewer/assets/92861079/2f71d921-fc48-475f-a271-b365381a06fa)
